# Generated by Django 4.2.6 on 2023-10-31 18:50

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bed_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='check_in_rqm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('documents', models.CharField(blank=True, choices=[('nid', 'NID Card'), ('passport', 'Passport')], max_length=20, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='room_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('persons', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='room_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='services_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hotelroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('size_type', models.CharField(blank=True, choices=[('foot', 'Foot'), ('meter', 'Meter')], max_length=5, null=True)),
                ('room_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('windows', models.PositiveIntegerField()),
                ('ac', models.BooleanField()),
                ('bedsheets', models.BooleanField(default=True)),
                ('celing_fan', models.BooleanField(default=True)),
                ('extra_fan', models.BooleanField(default=False)),
                ('extra_bed', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=True)),
                ('balcony', models.BooleanField(default=False)),
                ('balcony_size', models.PositiveIntegerField()),
                ('bed_opt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hotels.bed_option')),
                ('furniture', models.ManyToManyField(blank=True, to='Hotels.furniture')),
                ('room_cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hotels.room_cat')),
                ('room_view', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hotels.room_view')),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(default='default/default.png', upload_to='hotels/')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('road', models.TextField()),
                ('gmap_link', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('payment_option', models.CharField(choices=[('cash', 'Cash'), ('cards', 'Cards'), ('mblbnk', 'Mobile Banking')], max_length=10)),
                ('discount', models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat')], max_length=10)),
                ('pets', models.BooleanField()),
                ('parking', models.CharField(choices=[('selfprk', 'Self Parking')], max_length=20)),
                ('policies', models.TextField()),
                ('hotel_created_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateField()),
                ('check_in_rqm', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Hotels.check_in_rqm')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hotels.country')),
                ('facilities', models.ManyToManyField(to='Hotels.facilities')),
                ('faq', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hotels.faq')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotels.hotelroom')),
                ('services', models.ManyToManyField(to='Hotels.services')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facilities',
            name='category',
            field=models.ManyToManyField(max_length=30, to='Hotels.services_cat'),
        ),
    ]
