# Generated by Django 4.2.6 on 2023-10-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(to='Hotels.facilities'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(to='Hotels.services'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='furniture',
            field=models.ManyToManyField(blank=True, null=True, to='Hotels.furniture'),
        ),
    ]
